package com.diploma.chessing.enumeration;

public enum Piece {
    PAWN_WHITE, BISHOP_WHITE, KNIGHT_WHITE, ROOK_WHITE, QUEEN_WHITE, KING_WHITE,
    PAWN_BLACK, BISHOP_BLACK, KNIGHT_BLACK, ROOK_BLACK, QUEEN_BLACK, KING_BLACK
}
